Tell Travis you want a Python environment to test in
language: python
# List the versions of Python you'd like to test against
python:
  - "2.5"
  - "2.6"
  - "2.7"
# List the versions of Django you'd like to test against
env:
  - DJANGO_VERSION=1.4
# Tell it the things it will need to install when it boots
install: 
 - pip install Django==$DJANGO_VERSION
# Tell Travis how to run the test script itself
script: python test_project/runtests.py 
